### ISSUE TITLE
Handle environment variables in YAML config files

### ISSUE THREAD

**Issue by macbre** [macbre/optimist-config-file#1]
See https://github.com/macbre/phantomas/issues/685

- [x]  Move [optimist-config-file.js](https://github.com/macbre/phantomas/blob/devel/lib/optimist-config-file.js#L36) here
- [x] Add unit tests
- [x] Handle environment variables in YAML config files [the way Docker does it](https://docs.docker.com/compose/environment-variables/)

### Example

```yaml
url: ${HOST}/my-page
```

@rbayliss

**Comment by macbre** [comment]
Let's keep the `optimist-config-file.js` history:

```
cd repository
git log --pretty=email --patch-with-stat --reverse --full-index --binary -- path/to/file_or_folder > patch
cd ../another_repository
git am < ../repository/patch
```

**Comment by macbre** [comment]
Done

**Comment by XVincentX** [comment]
Hey — I just wanted to say I was looking for env replacement feature for another project I was working on and I found this function you implemented to fulfill the use case perfectly.

I know it's not that much — but I wanted to thank you for that. I've referenced the URL in the code itself. 🔝

**Comment by macbre** [comment]
Thanks, @XVincentX - that's much appreciated. Hope my code will serve you well :)

**Comment by XVincentX** [comment]
https://github.com/ExpressGateway/express-gateway/commit/0b562e76038300f0be924bb888ccd114933df3c0
